from fastapi import APIRouter, Depends, HTTPException, Path, Body
from typing import List, Optional
from motor.motor_asyncio import AsyncIOMotorDatabase
from bson import ObjectId
from datetime import datetime

from app.dependencies import get_db, get_current_user
from app.models.user import User
from app.models.chat import Chat, Message
from app.schemas.chat import ChatCreate, ChatResponse, MessageCreate, MessageResponse

router = APIRouter(
    prefix="/api/v1/chats",
    tags=["chats"]
)

@router.post("", response_model=ChatResponse)
async def create_chat(
    chat_data: Optional[ChatCreate] = Body(default=None),
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Create a new chat"""
    document_id = None
    if chat_data and chat_data.document_id:
        document_id = chat_data.document_id
    
    chat = Chat(
        user_id=current_user.id,
        document_id=document_id
    )
    
    # Insert chat into database
    chat_dict = chat.dict(by_alias=True)
    result = await db.chats.insert_one(chat_dict)
    chat_id = result.inserted_id
    
    # Add initial welcome message
    welcome_message = Message(
        chat_id=chat_id,
        role="assistant",
        content="Hello! I'm your document assistant. How can I help you today?"
    )
    
    # Insert message into database
    message_dict = welcome_message.dict(by_alias=True)
    await db.messages.insert_one(message_dict)
    
    # Get the chat with messages
    created_chat = await db.chats.find_one({"_id": chat_id})
    messages = await db.messages.find({"chat_id": chat_id}).to_list(length=100)
    
    # Return as Chat model
    chat_model = Chat(**created_chat)
    chat_model.messages = [Message(**msg) for msg in messages]
    
    return chat_model

@router.get("", response_model=List[ChatResponse])
async def get_user_chats(
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get all chats for the current user"""
    cursor = db.chats.find({"user_id": current_user.id})
    chats_data = await cursor.to_list(length=100)
    
    # Get messages for each chat
    result_chats = []
    for chat_data in chats_data:
        chat = Chat(**chat_data)
        messages = await db.messages.find({"chat_id": chat.id}).to_list(length=100)
        chat.messages = [Message(**msg) for msg in messages]
        result_chats.append(chat)
    
    return result_chats

@router.get("/{chat_id}", response_model=ChatResponse)
async def get_chat(
    chat_id: str = Path(...),
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get a specific chat by ID"""
    chat_data = await db.chats.find_one({
        "_id": ObjectId(chat_id),
        "user_id": current_user.id
    })
    
    if not chat_data:
        raise HTTPException(status_code=404, detail="Chat not found")
    
    # Get messages for this chat
    chat = Chat(**chat_data)
    messages = await db.messages.find({"chat_id": ObjectId(chat_id)}).to_list(length=100)
    chat.messages = [Message(**msg) for msg in messages]
    
    return chat

@router.post("/{chat_id}/messages", response_model=MessageResponse)
async def send_message(
    chat_id: str = Path(...),
    message_data: MessageCreate = Body(...),
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Send a message in a chat"""
    # Verify the chat exists and belongs to the user
    chat_data = await db.chats.find_one({
        "_id": ObjectId(chat_id),
        "user_id": current_user.id
    })
    
    if not chat_data:
        raise HTTPException(status_code=404, detail="Chat not found")
    
    # Save user message
    user_message = Message(
        chat_id=ObjectId(chat_id),
        role="user",
        content=message_data.content
    )
    
    user_message_dict = user_message.dict(by_alias=True)
    await db.messages.insert_one(user_message_dict)
    
    # Generate AI response (this is a simplified example)
    # In a real implementation, you would call your AI model here
    ai_response = "This is a sample response. In a real implementation, this would be generated by your AI model."
    
    # Save AI response
    ai_message = Message(
        chat_id=ObjectId(chat_id),
        role="assistant",
        content=ai_response
    )
    
    ai_message_dict = ai_message.dict(by_alias=True)
    result = await db.messages.insert_one(ai_message_dict)
    
    # Get the created message
    created_message = await db.messages.find_one({"_id": result.inserted_id})
    return Message(**created_message)

@router.post("/query", response_model=MessageResponse)
async def query_document(
    query_data: dict = Body(...),
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Query a document directly (without creating a chat)"""
    query = query_data.get("query")
    document_id = query_data.get("document_id")
    
    # This is a simplified example - you would call your AI model here
    # to generate a response based on the document content
    
    response = MessageResponse(
        role="assistant",
        content=f"This is a sample response to your query: '{query}'. In a real implementation, this would be generated by your AI model."
    )
    
    return response

@router.delete("/{chat_id}")
async def delete_chat(
    chat_id: str = Path(...),
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Delete a chat"""
    # Verify the chat exists and belongs to the user
    chat_data = await db.chats.find_one({
        "_id": ObjectId(chat_id),
        "user_id": current_user.id
    })
    
    if not chat_data:
        raise HTTPException(status_code=404, detail="Chat not found")
    
    # Delete associated messages
    await db.messages.delete_many({"chat_id": ObjectId(chat_id)})
    
    # Delete chat
    await db.chats.delete_one({"_id": ObjectId(chat_id)})
    
    return {"success": True}