from fastapi import APIRouter, Depends, HTTPException, Path, Body
from sqlalchemy.orm import Session
from typing import List, Optional

from app.core.database import get_db
from app.models.user import User
from app.models.chat import Chat, Message
from app.schemas.chat import ChatCreate, ChatResponse, MessageCreate, MessageResponse
from app.api.deps import get_current_user

router = APIRouter(
    prefix="/api/v1/chats",
    tags=["chats"]
)

@router.post("", response_model=ChatResponse)
async def create_chat(
    chat_data: Optional[ChatCreate] = Body(default=None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Create a new chat"""
    document_id = None
    if chat_data and chat_data.document_id:
        document_id = chat_data.document_id
    
    chat = Chat(
        user_id=current_user.id,
        document_id=document_id
    )
    
    db.add(chat)
    db.commit()
    db.refresh(chat)
    
    # Add initial welcome message
    welcome_message = Message(
        chat_id=chat.id,
        role="assistant",
        content="Hello! I'm your document assistant. How can I help you today?"
    )
    
    db.add(welcome_message)
    db.commit()
    
    # Return the chat with its messages
    chat = db.query(Chat).filter(Chat.id == chat.id).first()
    return chat

@router.get("", response_model=List[ChatResponse])
async def get_user_chats(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get all chats for the current user"""
    chats = db.query(Chat).filter(Chat.user_id == current_user.id).all()
    return chats

@router.get("/{chat_id}", response_model=ChatResponse)
async def get_chat(
    chat_id: int = Path(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get a specific chat by ID"""
    chat = db.query(Chat).filter(
        Chat.id == chat_id,
        Chat.user_id == current_user.id
    ).first()
    
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")
    
    return chat

@router.post("/{chat_id}/messages", response_model=MessageResponse)
async def send_message(
    chat_id: int = Path(...),
    message_data: MessageCreate = Body(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Send a message in a chat"""
    # Verify the chat exists and belongs to the user
    chat = db.query(Chat).filter(
        Chat.id == chat_id,
        Chat.user_id == current_user.id
    ).first()
    
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")
    
    # Save user message
    user_message = Message(
        chat_id=chat_id,
        role="user",
        content=message_data.content
    )
    
    db.add(user_message)
    db.commit()
    
    # Generate AI response (this is a simplified example)
    # In a real implementation, you would call your AI model here
    ai_response = "This is a sample response. In a real implementation, this would be generated by your AI model."
    
    # Save AI response
    ai_message = Message(
        chat_id=chat_id,
        role="assistant",
        content=ai_response
    )
    
    db.add(ai_message)
    db.commit()
    db.refresh(ai_message)
    
    return ai_message

@router.post("/query", response_model=MessageResponse)
async def query_document(
    query_data: dict = Body(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Query a document directly (without creating a chat)"""
    query = query_data.get("query")
    document_id = query_data.get("document_id")
    
    # This is a simplified example - you would call your AI model here
    # to generate a response based on the document content
    
    response = MessageResponse(
        role="assistant",
        content=f"This is a sample response to your query: '{query}'. In a real implementation, this would be generated by your AI model."
    )
    
    return response

@router.delete("/{chat_id}")
async def delete_chat(
    chat_id: int = Path(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Delete a chat"""
    chat = db.query(Chat).filter(
        Chat.id == chat_id,
        Chat.user_id == current_user.id
    ).first()
    
    if not chat:
        raise HTTPException(status_code=404, detail="Chat not found")
    
    # Delete associated messages
    db.query(Message).filter(Message.chat_id == chat_id).delete()
    
    # Delete chat
    db.delete(chat)
    db.commit()
    
    return {"success": True}